# Generated by Django 4.0.6 on 2022-07-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('vehicles', '0004_alter_vehicle_options_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_point', models.CharField(default='SKP', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('seating_capacity', models.IntegerField()),
                ('finish_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='destinations.destination')),
                ('unique_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
