# Generated by Django 4.0.6 on 2022-07-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
    ]
