# Generated by Django 4.0.6 on 2022-07-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_route_start_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.CharField(default='SKP', max_length=64),
        ),
    ]
