# Generated by Django 4.0.6 on 2022-08-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_start_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='finished_at',
        ),
    ]
