# Generated by Django 4.0.6 on 2022-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='finished_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
