# Generated by Django 4.0.6 on 2022-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='seating_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
