# Generated by Django 4.0.6 on 2022-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_route_seating_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='seating_capacity',
            field=models.IntegerField(default=2),
        ),
    ]
