# Generated by Django 4.0.6 on 2022-08-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_licence_plate'),
        ('routes', '0007_alter_route_seating_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
    ]
