# Generated by Django 4.0.6 on 2022-08-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('vehicles', '0005_alter_vehicle_licence_plate'),
        ('routes', '0009_alter_route_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='finish_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='route',
            name='unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
    ]
