# Generated by Django 4.0.6 on 2022-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=2)),
                ('licence_plate', models.CharField(max_length=7)),
                ('seating_capacity', models.IntegerField()),
            ],
        ),
    ]
