# Generated by Django 4.0.6 on 2022-07-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['unique_number']},
        ),
    ]
